name: 'Setup gh CLI'
description: 'Downloads, installs, and authenticates a specific version of the GitHub CLI (gh).'
author: 'Your Name or Org'

branding:
  icon: 'terminal'
  color: 'purple'

inputs:
  version:
    description: 'The version of gh CLI to install (e.g., "2.40.0", "latest").'
    required: false
    default: 'latest'
  token:
    description: >
      A GitHub token to authenticate the CLI.
      Defaults to the workflow's GITHUB_TOKEN.
      Set to empty string '' to skip authentication.
    required: false
    default: ${{ github.token }}

outputs:
  gh-path:
    description: 'The path to the installed gh executable.'
  version:
    description: 'The actual version of gh CLI that was installed.'

runs:
  using: 'composite'
  steps:
    - name: Install gh CLI and Set Outputs
      shell: bash
      # The script will now handle setting outputs directly.
      run: ${{ github.action_path }}/install.sh
      env:
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_TOKEN: ${{ inputs.token }}
